name: Covid Russia Stats

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Profile Gist with COVID Russia Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: puf17640/covid-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COUNTRY: ${{ secrets.COUNTRY }}
          GIST_ID: ${{ secrets.GIST_ID }}