name: RSS and Activity [RU]

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Markdown template
        uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Configure template type
          template: markdown
          filename: docs/README.md
          markdown: docs/template/README_TEMPLATE.md

          # Options
          user: SmithyVL
          base: ""
          config_timezone: Europe/Kirov
          plugin_activity: yes
          plugin_activity_filter: all
          plugin_activity_timestamps: yes
          plugin_rss: yes
          plugin_rss_source: https://habr.com/ru/rss/feed/243aceb23dd0da0d28f7cc4a656548a3?fl=ru&rating=10&types%5B%5D=article&types%5B%5D=post&types%5B%5D=news
          plugin_rss_limit: 10