name: Commits calendar

on:
  push:
    branches:
      - master
  schedule:
    - cron: "20 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Classic template
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Bangerok
          filename: docs/template/.cache/iso-calendar.*
          config_timezone: Europe/Kirov
          config_display: large
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year