name: Achievements

on:
  schedule:
    - cron: "30 3 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Classic template
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: Bangerok
          filename: assets/metrics/achievements.*
          config_display: columns
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: X